//! C++ code generation from anthill specifications.
//!
//! KB-driven (per `docs/proposals/029-rust-mapping-split.md`); profile
//! `cpp17-stl` per `docs/cpp-forward-mapping.md`. The "Known gaps"
//! section in that document is the authoritative list of unimplemented
//! mapping pieces (typeclass templates, parameterized types, sums,
//! effect lowering, traits-class method bodies for non-primitive
//! returns).
//!
//! Templates are `&'static str` constants near the top of the module
//! with `{name}` slots filled via `.replace`. Upgrade to askama/tera
//! when conditional/nested logic outgrows flat substitution.

use std::collections::HashMap;

use anthill_core::intern::Symbol;
use anthill_core::kb::KnowledgeBase;
use anthill_core::kb::term::{Literal, Term, TermId};
use anthill_core::kb::typing::extract_sort_ref_sym;

// ── Templates ────────────────────────────────────────────────────────
//
// Slots use `{name}` syntax. They are textually `.replace`d; no nesting,
// no escaping needed (C++ source we emit doesn't contain literal `{name}`
// at any slot position). Slot values must not themselves contain other
// slots that would be re-substituted — for current uses this is trivially
// safe (slots hold identifiers, type names, or already-rendered field
// blocks).

const TEMPLATE_ENTITY_STRUCT: &str = "\
struct {name} {
{fields}};
";

const TEMPLATE_FIELD: &str = "    {ty} {name};\n";

const TEMPLATE_HEADER: &str = "\
// Generated by anthill-cpp-gen — do not edit by hand.
// Source: anthill spec namespace `{ns_anthill}`.

#pragma once
{includes}
namespace {ns_cpp} {

{items}}  // namespace {ns_cpp}
";

const TEMPLATE_TRAITS_STRUCT: &str = "\
struct {name} {
{methods}};
";

const TEMPLATE_STATIC_METHOD_DECL: &str = "    static {ret} {name}({params});\n";

// Note: deliberately no `\<newline>` line-continuation here — that
// would strip the leading 4-space indent. The literal starts with
// the four spaces as written.
const TEMPLATE_STATIC_METHOD_BODY: &str = "    static {ret} {name}({params}) {
        {body}
    }
";

// ── Errors ───────────────────────────────────────────────────────────

#[derive(Debug, Clone)]
pub struct CppCodegenError {
    pub message: String,
}

impl std::fmt::Display for CppCodegenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.message)
    }
}

impl std::error::Error for CppCodegenError {}

// ── Carrier table & codegen context ──────────────────────────────────

/// Resolved table of qualified-anthill-sort-name → C++ host type,
/// built from `Implementation` + `CarrierBinding` facts in the KB.
///
/// Currently captures the *self-carrier* of each Implementation: when
/// `Implementation(target: "X", carrier: [CarrierBinding(sort_name: "X_short", host_type: "Y")])`
/// is asserted, `lookup("X")` returns `Some("Y")`. Sub-sort carriers
/// (CarrierBindings whose sort_name is not the target's short name)
/// are not yet wired through — extending this is mechanical when a
/// concrete consumer needs it.
///
/// Only Implementation facts with `language: "cpp"` participate.
pub struct CarrierTable {
    by_qualified: HashMap<String, String>,
}

impl CarrierTable {
    /// Build the table by scanning the KB's `Implementation` facts.
    /// Returns an empty table if no `Implementation` symbol is in the
    /// KB (i.e. the realization stdlib wasn't loaded).
    pub fn from_kb(kb: &KnowledgeBase) -> Self {
        let mut by_qualified = HashMap::new();

        let impl_sym = kb
            .try_resolve_symbol("anthill.realization.Implementation")
            .or_else(|| kb.try_resolve_symbol("Implementation"));
        let Some(impl_sym) = impl_sym else {
            return Self { by_qualified };
        };

        for rid in kb.by_functor(impl_sym) {
            let head = kb.rule_head(rid);

            let target = match named_string(kb, head, "target") {
                Some(t) => t,
                None => continue,
            };
            let language = named_string(kb, head, "language");
            if language.as_deref() != Some("cpp") {
                continue;
            }

            let carrier_list = match named_arg(kb, head, "carrier") {
                Some(t) => t,
                None => continue,
            };
            let target_short = target
                .rsplit('.')
                .next()
                .unwrap_or(&target)
                .to_string();

            for binding in walk_list(kb, carrier_list) {
                let sort_name = named_string(kb, binding, "sort_name");
                let host_type = named_string(kb, binding, "host_type");
                if let (Some(sn), Some(ht)) = (sort_name, host_type) {
                    // For now: only the self-carrier (sort_name == target's
                    // short name) lands in the table keyed by `target`.
                    // Sub-sort carriers will get their own keys when needed.
                    if sn == target_short {
                        by_qualified.insert(target.clone(), ht);
                    }
                }
            }
        }

        Self { by_qualified }
    }

    /// Look up a host type by the anthill sort's fully qualified name.
    pub fn lookup(&self, qualified: &str) -> Option<&str> {
        self.by_qualified.get(qualified).map(|s| s.as_str())
    }

    /// Whether the table has any entries (used by tests).
    pub fn is_empty(&self) -> bool {
        self.by_qualified.is_empty()
    }
}

/// Bundles the KB with a derived `CarrierTable` so emit functions
/// don't have to re-scan facts on every type lookup. Construct once
/// per codegen run; pass to every emit function.
pub struct CodegenContext<'kb> {
    pub kb: &'kb KnowledgeBase,
    pub carriers: CarrierTable,
}

impl<'kb> CodegenContext<'kb> {
    pub fn new(kb: &'kb KnowledgeBase) -> Self {
        Self {
            kb,
            carriers: CarrierTable::from_kb(kb),
        }
    }
}

// ── Term inspection helpers ──────────────────────────────────────────

/// Get the value of a named argument from a `Term::Fn` head.
fn named_arg(kb: &KnowledgeBase, head: TermId, name: &str) -> Option<TermId> {
    if let Term::Fn { named_args, .. } = kb.get_term(head) {
        for (sym, val) in named_args {
            if kb.resolve_sym(*sym) == name {
                return Some(*val);
            }
        }
    }
    None
}

/// Pull a `Literal::String` out of a term, if that's what it is.
fn as_string(kb: &KnowledgeBase, term: TermId) -> Option<String> {
    if let Term::Const(Literal::String(s)) = kb.get_term(term) {
        Some(s.clone())
    } else {
        None
    }
}

/// Combination of `named_arg` + `as_string`.
fn named_string(kb: &KnowledgeBase, head: TermId, name: &str) -> Option<String> {
    named_arg(kb, head, name).and_then(|t| as_string(kb, t))
}

/// Return the qualified name of `sym`'s parent, if any — e.g.
/// `test.geom.Vec3.x` → `Some("test.geom.Vec3")`. Used in lieu of
/// `SymbolTable::scope_of`, which has buggy semantics (finds a
/// sibling in the same scope, not the parent).
fn parent_qualified_name(kb: &KnowledgeBase, sym: Symbol) -> Option<String> {
    let qn = kb.qualified_name_of(sym);
    qn.rsplit_once('.').map(|(parent, _)| parent.to_string())
}

/// Walk a list-shaped term and collect element TermIds. Recognises:
///   - `ListLiteral(a, b, ...)` — pre-typing parser output
///   - `cons(head: ..., tail: ...)` — typed list form using named args
///   - `cons(head, tail)` — typed list form using positional args
///   - `nil` — list terminator
///
/// Anything else returns whatever has been collected so far.
fn walk_list(kb: &KnowledgeBase, list: TermId) -> Vec<TermId> {
    let mut out = Vec::new();
    let mut current = list;
    loop {
        let term = kb.get_term(current);
        let Term::Fn { functor, pos_args, named_args } = term else { return out };
        match kb.resolve_sym(*functor) {
            "ListLiteral" => {
                for arg in pos_args {
                    out.push(*arg);
                }
                return out;
            }
            "cons" => {
                // Try named args first (head:/tail:), fall back to positional.
                let head = named_args
                    .iter()
                    .find(|(s, _)| kb.resolve_sym(*s) == "head")
                    .map(|(_, v)| *v)
                    .or_else(|| pos_args.first().copied());
                let tail = named_args
                    .iter()
                    .find(|(s, _)| kb.resolve_sym(*s) == "tail")
                    .map(|(_, v)| *v)
                    .or_else(|| pos_args.get(1).copied());
                match (head, tail) {
                    (Some(h), Some(t)) => {
                        out.push(h);
                        current = t;
                    }
                    _ => return out,
                }
            }
            "nil" => return out,
            _ => return out,
        }
    }
}

// ── Public API ───────────────────────────────────────────────────────

/// Emit a C++ struct for a single anthill entity, looked up by name.
/// The name may be either short ("Vec3") or fully qualified
/// ("test.geom.Vec3"); the C++ struct is named with the short
/// component, regardless of which form was passed in.
///
/// Convenience wrapper: builds a fresh `CodegenContext` from `kb`
/// (which scans `Implementation` facts). For repeated calls in one
/// codegen run, build the context once and use the by-symbol API.
pub fn emit_entity_struct(
    kb: &KnowledgeBase,
    entity_name: &str,
) -> Result<String, CppCodegenError> {
    let ctx = CodegenContext::new(kb);
    let sym = kb.try_resolve_symbol(entity_name).ok_or_else(|| {
        CppCodegenError {
            message: format!("entity '{entity_name}' not found in KB"),
        }
    })?;
    emit_entity_struct_by_symbol(&ctx, sym)
}

/// Emit a C++ struct for an entity given its functor Symbol.
/// The struct's C++ name is the short (final) component of the
/// resolved qualified name, so callers cannot accidentally inject
/// a dotted path as the struct identifier.
pub fn emit_entity_struct_by_symbol(
    ctx: &CodegenContext,
    functor: Symbol,
) -> Result<String, CppCodegenError> {
    let kb = ctx.kb;
    let qualified = kb.qualified_name_of(functor);
    let display_name = qualified.rsplit('.').next().unwrap_or(qualified);

    let fields = kb.entity_field_types(functor).ok_or_else(|| {
        CppCodegenError {
            message: format!(
                "'{qualified}' has no registered fields — is it really an entity?"
            ),
        }
    })?;

    let mut fields_text = String::new();
    for (field_sym, type_term) in fields {
        let cpp_type = lower_type(ctx, *type_term)?;
        let field_name = kb.resolve_sym(*field_sym);
        fields_text.push_str(
            &TEMPLATE_FIELD
                .replace("{ty}", &cpp_type)
                .replace("{name}", field_name),
        );
    }

    Ok(TEMPLATE_ENTITY_STRUCT
        .replace("{name}", display_name)
        .replace("{fields}", &fields_text))
}

// ── Traits-class (sort-with-operations) emission ────────────────────

/// Emit a C++ "traits-class" struct exposing every operation of a
/// sort as a `static` method declaration. Convenience wrapper that
/// builds a fresh `CodegenContext`.
///
/// Today emits declarations only — no method bodies. Body generation
/// (calling into the carrier with `self->method(args)`) needs a
/// snake-to-camel naming convention which is part of WI-088 / WI-089.
/// Until then, the user fills bodies manually or hand-writes the
/// implementation file.
pub fn emit_traits_struct(
    kb: &KnowledgeBase,
    sort_name: &str,
) -> Result<String, CppCodegenError> {
    let ctx = CodegenContext::new(kb);
    let sym = kb.try_resolve_symbol(sort_name).ok_or_else(|| {
        CppCodegenError {
            message: format!("sort '{sort_name}' not found in KB"),
        }
    })?;
    emit_traits_struct_by_symbol(&ctx, sym)
}

/// Emit a traits-class struct for a sort given its functor Symbol.
/// Uses the sort's short (final) qualified-name component as the C++
/// struct name. Returns an error if the sort has no operations in
/// its scope.
pub fn emit_traits_struct_by_symbol(
    ctx: &CodegenContext,
    sort_sym: Symbol,
) -> Result<String, CppCodegenError> {
    let kb = ctx.kb;
    let qualified = kb.qualified_name_of(sort_sym);
    let display_name = qualified.rsplit('.').next().unwrap_or(qualified);

    let ops = operations_in_sort(ctx, sort_sym)?;
    if ops.is_empty() {
        return Err(CppCodegenError {
            message: format!(
                "sort '{qualified}' has no operations — \
                 a traits struct would be empty"
            ),
        });
    }

    let mut methods_text = String::new();
    for op in &ops {
        let params_text = op.params.iter()
            .map(|p| format!("{} {}", p.cpp_type, p.name))
            .collect::<Vec<_>>()
            .join(", ");
        let rendered = match &op.body {
            Some(body) => TEMPLATE_STATIC_METHOD_BODY
                .replace("{ret}", &op.return_type_cpp)
                .replace("{name}", &op.name)
                .replace("{params}", &params_text)
                .replace("{body}", body),
            None => TEMPLATE_STATIC_METHOD_DECL
                .replace("{ret}", &op.return_type_cpp)
                .replace("{name}", &op.name)
                .replace("{params}", &params_text),
        };
        methods_text.push_str(&rendered);
    }

    Ok(TEMPLATE_TRAITS_STRUCT
        .replace("{name}", display_name)
        .replace("{methods}", &methods_text))
}

/// One operation's signature, as needed for traits-class emission.
/// `body` is `Some` when we can synthesise a definition that calls
/// into the carrier; `None` otherwise (declaration-only).
struct OperationSig {
    name: String,
    params: Vec<ParamInfo>,
    return_type_cpp: String,
    body: Option<String>,
}

struct ParamInfo {
    name: String,
    cpp_type: String,
}

/// True if a C++ type is one of the spellings produced by `prim_lower`.
/// Used to decide whether an operation's body can be synthesised
/// without a marshalling step (Vec3 from `const double *` etc.).
/// Single source of truth: walks the `prim_lower` table.
fn return_is_primitive(cpp_type: &str) -> bool {
    PRIMITIVE_ANTHILL_NAMES
        .iter()
        .any(|name| prim_lower(name) == Some(cpp_type))
}

/// All anthill primitive sort short names. The `prim_lower` table
/// is the source of truth for the C++ spelling each maps to.
const PRIMITIVE_ANTHILL_NAMES: &[&str] =
    &["Int", "Float", "Bool", "String", "Unit"];

/// Convert a snake_case identifier to camelCase. Naive transform —
/// drops underscores and uppercases the next char. Does not preserve
/// acronyms (`get_gps` → `getGps`, not `getGPS`). Per-operation
/// overrides will arrive with WI-087 attributes; until then,
/// acronym-heavy ops emit the wrong C++ method name and need a
/// hand-edit. Documented in the cpp-forward-mapping spec.
fn snake_to_camel(snake: &str) -> String {
    let mut out = String::with_capacity(snake.len());
    let mut upper_next = false;
    for c in snake.chars() {
        if c == '_' {
            upper_next = true;
        } else if upper_next {
            out.extend(c.to_uppercase());
            upper_next = false;
        } else {
            out.push(c);
        }
    }
    out
}

/// Synthesise a method body for an op whose first arg is `self` and
/// whose return type is a primitive (or void). Returns `None` for ops
/// we can't safely lower yet — declaration-only. The returned string
/// is the *inside* of the method; the template adds the outer braces.
///
/// Skipped cases:
///   - first param is not named `self` — no dispatch target
///   - return type isn't a primitive — needs marshalling (WI-088)
fn synthesise_body_for(name: &str, params: &[ParamInfo], return_type: &str) -> Option<String> {
    let self_param = params.first()?;
    if self_param.name != "self" {
        return None;
    }
    if !return_is_primitive(return_type) {
        return None;
    }
    let arrow = if self_param.cpp_type.contains('*') { "->" } else { "." };
    let cpp_method = snake_to_camel(name);
    let non_self_args = params.iter().skip(1)
        .map(|p| p.name.as_str())
        .collect::<Vec<_>>()
        .join(", ");
    let call = format!("self{arrow}{cpp_method}({non_self_args})");
    Some(if return_type == "void" {
        format!("{call};")
    } else {
        format!("return {call};")
    })
}

/// Walk the KB's `OperationInfo` facts and return all that belong to
/// `sort_sym`'s scope. Each entry's params and return type are lowered
/// via the carrier-aware `lower_type`.
fn operations_in_sort(
    ctx: &CodegenContext,
    sort_sym: Symbol,
) -> Result<Vec<OperationSig>, CppCodegenError> {
    let kb = ctx.kb;
    let op_info_sym = match kb.try_resolve_symbol("anthill.reflect.OperationInfo") {
        Some(s) => s,
        None => return Ok(Vec::new()),
    };
    let qualified = kb.qualified_name_of(sort_sym).to_string();

    let mut out = Vec::new();
    for rid in kb.by_functor(op_info_sym) {
        let head = kb.rule_head(rid);

        let name_term = match named_arg(kb, head, "name") {
            Some(t) => t,
            None => continue,
        };
        let op_sym = match kb.get_term(name_term) {
            Term::Ref(s) => *s,
            _ => continue,
        };
        // The operation's parent sort is the prefix of its qualified
        // name (test.simple.Greeter.count → test.simple.Greeter).
        // We don't use SymbolTable::scope_of because that helper finds
        // a *sibling* symbol in the same scope, not the parent.
        if parent_qualified_name(kb, op_sym) != Some(qualified.to_string()) {
            continue;
        }

        let name = kb.resolve_sym(op_sym).to_string();

        let return_term = named_arg(kb, head, "return_type").ok_or_else(|| {
            CppCodegenError {
                message: format!("operation '{name}' missing return_type"),
            }
        })?;
        let return_type_cpp = lower_type(ctx, return_term)?;

        let params_term = named_arg(kb, head, "params");
        let mut params = Vec::new();
        if let Some(plist) = params_term {
            for finfo in walk_list(kb, plist) {
                let p_name = match named_arg(kb, finfo, "name") {
                    Some(t) => match kb.get_term(t) {
                        Term::Ref(s) => kb.resolve_sym(*s).to_string(),
                        _ => continue,
                    },
                    None => continue,
                };
                let p_type = match named_arg(kb, finfo, "type_name") {
                    Some(t) => t,
                    None => continue,
                };
                let cpp_type = lower_type(ctx, p_type)?;
                params.push(ParamInfo { name: p_name, cpp_type });
            }
        }

        let body = synthesise_body_for(&name, &params, &return_type_cpp);
        out.push(OperationSig { name, params, return_type_cpp, body });
    }

    out.sort_by(|a, b| a.name.cmp(&b.name));
    Ok(out)
}

// ── Namespace header emission ────────────────────────────────────────

/// Emit a complete C++ header file for every entity declared directly
/// under the given anthill namespace. Output includes `#pragma once`,
/// the minimum set of standard-library includes implied by emitted
/// types, and a `namespace foo::bar { ... }` wrapper.
///
/// Anthill `foo.bar.Baz` becomes C++ `foo::bar` (C++17 nested-namespace
/// syntax). Entities are emitted in qualified-name order for
/// determinism.
///
/// Returns an error if no entities are found under the namespace
/// (catches typos / wrong namespace strings before they produce empty
/// headers).
pub fn emit_namespace_header(
    kb: &KnowledgeBase,
    namespace: &str,
) -> Result<String, CppCodegenError> {
    let ctx = CodegenContext::new(kb);
    emit_namespace_header_in(&ctx, namespace)
}

/// Like `emit_namespace_header` but reuses an existing context.
/// Prefer this when emitting multiple namespaces in one run.
pub fn emit_namespace_header_in(
    ctx: &CodegenContext,
    namespace: &str,
) -> Result<String, CppCodegenError> {
    let entities = entities_directly_in(ctx, namespace);
    if entities.is_empty() {
        return Err(CppCodegenError {
            message: format!(
                "no entities to emit directly under namespace '{namespace}' \
                 (either no entities are declared there, or all of them are \
                 carrier-bound by Implementation facts)"
            ),
        });
    }

    let mut items = String::new();
    let mut needs = Includes::default();
    for sym in entities {
        let struct_text = emit_entity_struct_by_symbol(ctx, sym)?;
        needs.scan(&struct_text);
        items.push_str(&struct_text);
        items.push('\n');
    }

    let ns_cpp = namespace.replace('.', "::");
    Ok(TEMPLATE_HEADER
        .replace("{ns_anthill}", namespace)
        .replace("{ns_cpp}", &ns_cpp)
        .replace("{includes}", &needs.render())
        .replace("{items}", &items))
}

/// Find entities whose qualified name is exactly `<namespace>.<short>`,
/// excluding any that have a `CarrierBinding` (those map to a host-side
/// type and must NOT be emitted as a fresh struct, or the generated
/// header would shadow the user's existing type).
fn entities_directly_in(ctx: &CodegenContext, namespace: &str) -> Vec<Symbol> {
    let kb = ctx.kb;
    let prefix = format!("{namespace}.");
    let mut out: Vec<Symbol> = kb
        .entity_field_type_functors()
        .copied()
        .filter(|sym| {
            let qualified = kb.qualified_name_of(*sym);
            qualified.starts_with(&prefix)
                && !qualified[prefix.len()..].contains('.')
                && ctx.carriers.lookup(qualified).is_none()
        })
        .collect();
    out.sort_by(|a, b| {
        kb.qualified_name_of(*a).cmp(kb.qualified_name_of(*b))
    });
    out
}

/// Set of standard-library headers required by emitted types. Built
/// up by scanning emitted struct text for primitive type spellings —
/// good enough for v0; will become fact-driven once cpp_std (WI-089)
/// makes the type ↔ header mapping data instead of code.
#[derive(Default)]
struct Includes {
    cstdint: bool,  // int64_t
    string: bool,   // std::string
}

impl Includes {
    fn scan(&mut self, text: &str) {
        if text.contains("int64_t") {
            self.cstdint = true;
        }
        if text.contains("std::string") {
            self.string = true;
        }
    }

    /// Render the include block with a leading newline (so the slot in
    /// the header template doesn't introduce a blank line when empty).
    fn render(&self) -> String {
        let mut out = String::new();
        if self.cstdint {
            out.push_str("\n#include <cstdint>");
        }
        if self.string {
            out.push_str("\n#include <string>");
        }
        out.push('\n');
        out
    }
}

// ── Type lowering ────────────────────────────────────────────────────

/// Lower an anthill type term to a C++ type expression.
///
/// Field types in entity declarations are wrapped as
/// `sort_ref(name: <symbol>)` by the loader. Bare `Term::Ref` /
/// `Term::Ident` are also accepted for robustness.
fn lower_type(ctx: &CodegenContext, type_term: TermId) -> Result<String, CppCodegenError> {
    let kb = ctx.kb;
    if let Some(sym) = extract_sort_ref_sym(kb, type_term) {
        return sort_to_cpp(ctx, sym);
    }

    let term = kb.get_term(type_term);
    match term {
        Term::Ref(sym) | Term::Ident(sym) => sort_to_cpp(ctx, *sym),
        Term::Fn { functor, .. } => {
            // extract_sort_ref_sym already handled the sort_ref wrapper,
            // so any remaining Fn is a parameterized type (List[T = X],
            // etc.). Deferred until cpp_std lands the data-driven table.
            let qualified = kb.qualified_name_of(*functor);
            let short = qualified.rsplit('.').next().unwrap_or(qualified);
            Err(CppCodegenError {
                message: format!(
                    "parameterized type lowering not yet implemented (got '{short}')"
                ),
            })
        }
        other => Err(CppCodegenError {
            message: format!("cannot lower term to C++ type: {other:?}"),
        }),
    }
}

/// Map a sort symbol to its C++ type spelling. Lookup order:
///   1. `CarrierTable` (from `Implementation` / `CarrierBinding` facts)
///   2. Hardcoded prelude primitives (`prim_lower`)
///   3. Project-local entity → its short name (the struct we emit
///      ourselves lives in the same C++ namespace)
///   4. Error
///
/// Carrier bindings take precedence — a user-supplied
/// `CarrierBinding(sort_name: "Int", host_type: "int32_t")` overrides
/// the default `Int → int64_t` mapping. The primitive table is the
/// fallback, not a constraint. Will become entirely fact-driven once
/// cpp_std (WI-089) lands a primitive `LanguageMapping`.
fn sort_to_cpp(ctx: &CodegenContext, sym: Symbol) -> Result<String, CppCodegenError> {
    let qualified = ctx.kb.qualified_name_of(sym);
    if let Some(host) = ctx.carriers.lookup(qualified) {
        return Ok(host.to_string());
    }
    let short = qualified.rsplit('.').next().unwrap_or(qualified);
    if let Some(prim) = prim_lower(short) {
        return Ok(prim.to_string());
    }
    // Project-local entity? Use its short name. The matching `struct`
    // is emitted by emit_entity_struct in the same C++ namespace.
    if ctx.kb.entity_field_types(sym).is_some() {
        return Ok(short.to_string());
    }
    Err(CppCodegenError {
        message: format!(
            "no C++ mapping for sort '{qualified}' — add a CarrierBinding \
             via an Implementation fact, or model it as an entity with fields"
        ),
    })
}

/// Prelude primitive name → C++ type name. None for non-primitives.
fn prim_lower(short_name: &str) -> Option<&'static str> {
    Some(match short_name {
        "Int" => "int64_t",
        "Float" => "double",
        "Bool" => "bool",
        "String" => "std::string",
        "Unit" => "void",
        _ => return None,
    })
}
