//! Embedded standard library sources for the `anthill` CLI.
//!
//! The `(label, source)` list is GENERATED at build time by `build.rs`, which
//! walks `stdlib/anthill/` and `anthill-stl/anthill/` and `include_str!`s every
//! `.anthill` file. This keeps the embedded set in lock-step with the live
//! stdlib — the former hand-maintained list drifted (missing `prelude/cell`,
//! `kernel`, `logic/*`, …), shipping a stale stdlib. Use
//! `parse_embedded_stdlib()` to get the parsed files.

use anthill_core::parse;
use anthill_core::parse::ir::ParsedFile;

/// `(label, source)` for every embedded `.anthill` file. The label is a
/// human-readable path used only in parse-error messages. Generated by
/// `build.rs` into `$OUT_DIR/stdlib_sources.rs`.
static STDLIB_SOURCES: &[(&str, &str)] = include!(concat!(env!("OUT_DIR"), "/stdlib_sources.rs"));

/// Parse all embedded stdlib sources. Returns (parsed files, warnings).
pub fn parse_embedded_stdlib() -> (Vec<ParsedFile>, Vec<String>) {
    let mut files = Vec::new();
    let mut errors = Vec::new();

    for &(path, source) in STDLIB_SOURCES {
        match parse::parse(source) {
            Ok(parsed) => files.push(parsed),
            Err(errs) => {
                for e in &errs {
                    errors.push(format!("stdlib {path}: {e}"));
                }
            }
        }
    }

    (files, errors)
}
